### PR TITLE
Development

### PR DESCRIPTION
**Pull request by IBUNHABIBU**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Congrats team 👏
You did nicely on this project. But Microverse guidelines require some changes on it before submitting to master. The changes are:

### Your page should have at least 3 breakpoints, up to 480px, 768px to 1024px and larger than 1024px. 
### The 3 breakpoint must have the same style and similar apperance from the original page. (In all section of the page).

- Navigation bar

- [ ] The navbar at this breakpoint should look similar to the original one:

image

image

image


- [ ] It should use fixed positioning

- [ ] It should display the TNW logo at the leftmost part of it

- [ ] It should have a search icon and a hamburger (bars) icon at the rightmost part of it

- [ ] The middle section of the navbar should be empty

- [ ]  Should match the style from the original page in at least the 3 breakpoints.

- Top Stories section

- [ ] It should have three stories, each one wrapped around a pair of `article`

- [ ] Should match the style from the original page in at least the 3 breakpoints.

image

image

image

- Latest News section

- [ ] It should have eight articles, each one wrapped around a pair of `article`

- [ ] Should match the original style in all 3 breakpoints.

- Latest Funding section

- [ ] It should be wrapped around a pair of its own `section`

- [ ] It should have three articles, each one wrapped around a pair of `article`

- [ ]  Should match the style from the original page in at least the 3 breakpoints.

- Apps section (gear, tech, creative...)

- [ ] It should be wrapped around a pair of its own `section`

- [ ] It should have eight articles, each one wrapped around a pair of `article`

- [ ]  Should match the style from the original page in at least the 3 breakpoints.

- Latest Deals section

- [ ] It should be wrapped around a pair of its own `section`

- [ ] It should have eight articles, each one wrapped around a pair of `article`

- [ ]  Should match the style from the original page in at least the 3 breakpoints.

Kindly make these changes and submit for code review again. Nice coding.

**Comment by IBUNHABIBU** [comment]
Thank you for your review.
Let me work on it

Tarehe Jumatatu, Jul 22, 2019 saa 15:10 Sérgio Torres <
notifications@github.com> aliandika:

**Comment by IBUNHABIBU** [comment]
Hi
I'm getting troubles with this project I used a lot of time to adjust those
snags.
May you help me the following ideas
1. The blank white space appear to the right of the page when I inspect the
element.
2. I have no enough knowledge to freeze the nav bar when I make position
fixed the white nav bar it won't appear as espected
3. Also to freeze the nwt logo when choose screen size table.
I hope you will help me
Best regards
Salum Habibu

Tarehe Jumatatu, Jul 22, 2019 saa 15:10 Sérgio Torres <
notifications@github.com> aliandika:

**Comment by IBUNHABIBU** [comment]
Hi
I'm getting troubles with this project I used a lot of time to adjust those
snags.
May you help me the following ideas
1. The blank white space appear to the right of the page when I inspect the
element.
2. I have no enough knowledge to freeze the nav bar when I make position
fixed the white nav bar it won't appear as espected
3. Also to freeze the nwt logo when choose screen size table.
I hope you will help me
Best regards
Salum Habibu


Tarehe Jumatatu, Jul 22, 2019 saa 14:07 Sérgio Torres <
notifications@github.com> aliandika:

**Comment by Torres-ssf** [comment]
Hi there @IBUNHABIBU 
I didn't see your message on the pull request early
I'm sorry about that. I'm going to message you on the slack

**Comment by Torres-ssf** [comment]
It will be easier for you to use flex instead grid as display to organize your page since flex is a bit simple to understand.
1- An easy way to make containers responsive is to make the row take 100%(or the desired one) of the width and give to its children the appropriate width. Example, if in the largest breakpoint you have 4 items per row, give 100% to father container and 25% to each child. You can use breakpoints to change these values. Remember that paddings can affect the size of the element unless you change the value of box-sizing to border-box. This [guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) has everything you need to know to become a pro with flexbox.
2- I see that you already fixed you navbar
3 - You don't need to make the logo have the same behavior from the original page. You don't need to display the logo in the largest breakpoint(In this breakpoint the logo is inside the first article). Just display it in the navbar in the other 2 breakpoints. 

I'm really sorry to take too long to answer you. I didn't see the message early. Please if you have any other issues with this project, message me on slack.

**Comment by bolah2009** [comment]
Currently under review

**Review by bolah2009 — APPROVED** [review]
## Nice Job so far :+1: 

The [clone](https://raw.githack.com/IBUNHABIBU/RESPONSIVE-DESIGN/development/index.html) is responsive but still have some minor issues, an example is the navbar for small screens. Feel free to reach me or (@Torres-ssf ) on slack if you having issues with making the page more responsive.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

**Pull request merged**
